# Generated by Django 4.1.6 on 2023-02-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersmanagement', '0002_trader_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsManagementClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_changed', models.DecimalField(decimal_places=3, max_digits=10)),
                ('actual_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanagement.clients')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanagement.trader')),
            ],
            options={
                'verbose_name': 'Log del cliente ',
                'verbose_name_plural': 'Logs de los clientes',
                'db_table': 'AssetsClientsManagement',
                'ordering': ['-date_added'],
            },
        ),
    ]
